name: NanoPi-R5S RK3568 OpenWrt v22.03 Build

on:
  push:
    paths:
      - 'CHANGELOG.md'
      - '.github/workflows/NanoPi_R5S_Build.yml'

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          sudo docker image prune -a -f
          sudo apt-get -y install upx-ucl unzip
          sudo apt-get -y purge dotnet* ghc* google* llvm* mysql* php* zulu* firefox hhvm
          sudo apt-get -y autoremove --purge
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash

      #- name: Setup Debug Session
      #  uses: P3TERX/debugger-action@master

      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/

      - name: Download Source
        run: |
          rm -rf R5s
          mkdir R5s
          cd R5s
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v22.03 -m rk3568.xml --repo-url=https://github.com/friendlyarm/repo  --no-clone-bundle
          repo sync -c --no-clone-bundle -j8


      - name: Install Extra Packages
        run: |
          cd R5s
          git clone --depth=1 https://github.com/kiddin9/openwrt-packages
          mkdir friendlywrt/package/custom
          pushd friendlywrt/package/custom
          mkdir passwall
          svn export https://github.com/coolsnowwolf/lede/trunk/package/lean/autocore ./autocore
          git clone https://github.com/fw876/helloworld.git
          pushd helloworld
          git checkout b4ede27bc2665208b7c5b2901abab55ea780d7b3
          popd
          popd
          cp -r openwrt-packages/{dns2socks,microsocks,ipt2socks,redsocks2} friendlywrt/package/custom/helloworld
          cp -r openwrt-packages/{luci-app-passwall,brook,chinadns-ng,hysteria,pdnsd-alt,trojan-plus,v2ray-geodata} friendlywrt/package/custom/passwall
          cp -r openwrt-packages/{luci-app-adguardhome,luci-app-nfs,luci-app-serverchan} friendlywrt/package/custom
          cp -r openwrt-packages/{luci-theme-argon,luci-app-argon-config} friendlywrt/package/custom
      - name: Update Target.mk
        run: |
          cd R5s

      - name: Update Feeds
        run: |
          cd R5s

      - name: Install Mods
        run: |
          cd R5s

      - name: Patch
        run: |
          cd R5s

      - name: Custom config files
        run: |
          cd R5s
          rm ./configs/rockchip/02-luci_lang
          rm ./configs/rockchip-docker/02-luci_lang
          cp ../config/10-plugins ./configs/rockchip/10-plugins
          cp ../config/10-plugins ./configs/rockchip-docker/10-plugins
          cp ../img/uboot.img ./u-boot/
          sed -i '/function build_all.*$/{n;s/build_uboot//;n;s/build_kernel//;}'  ./scripts/build.sh
          sed -i 's/make -j$(nproc)/make -j8/'  ./scripts/mk-friendlywrt.sh
          sed -i 's/ROOTFS_PARTSIZE.*$/ROOTFS_PARTSIZE=768/' ./configs/rockchip/01-nanopi
          sed -i 's/ROOTFS_PARTSIZE.*$/ROOTFS_PARTSIZE=768/' ./configs/rockchip-docker/01-nanopi

      - name: Set Default Values
        run: |
          cd R5s/friendlywrt

      - name: Build Kernel
        run: |
          cd R5s
          MK_LINK=".current_config.mk"
          ln -s ./device/friendlyelec/rk3568/nanopi_r5s.mk ${MK_LINK}
          source ${MK_LINK}
          ./build.sh kernel

      - name: Build OpenWrt
        run: |
          cd R5s
          echo -e "$(nproc) thread compile"
          ./build.sh rk3568_docker.mk

      - name: Fix Rootfs Owner and Group
        run: |
          sudo df -lh

      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find R5s/out/ -name "FriendlyWrt_*img*" | xargs -I{} sh -c 'f=$(basename $1); zip -r -j "./artifact/${f}.zip" $1' sh {} \;
          cp R5s/friendlywrt/.config ./artifact/

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: FriendlyWrt_NanoPi-R5S rk3568 v22.03
          path: ./artifact/

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@main
        with:
          name: OpenWRT-R5s-sd-img
          allowUpdates: true
          prerelease: true
          tag: ${{ 22.03 }}
          commit: 22.03
          replacesArtifacts: true
          token: ${{ secrets.ACCESS_TOKEN }}
          artifacts: ./artifact/*.zip
