name: NanoPi-R5S RK3568 OpenWrt v22.03 Build

on:
  push:
    paths:
      - 'CHANGELOG.md'
      - '.github/workflows/NanoPi_R5S_Build.yml'

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          sudo docker image prune -a -f
          sudo apt-get -y install upx-ucl unzip
          sudo apt-get -y purge dotnet* ghc* google* llvm* mysql* php* zulu* firefox hhvm
          sudo apt-get -y autoremove --purge
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash

      #- name: Setup Debug Session
      #  uses: P3TERX/debugger-action@master

      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/

      - name: Download Source
        run: |
          rm -rf R5s
          mkdir R5s
          cd R5s
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v22.03 -m rk3568.xml --repo-url=https://github.com/friendlyarm/repo  --no-clone-bundle
          repo sync -c --no-clone-bundle -j8


      - name: Install Extra Packages
        run: |
          cd R5s/friendlywrt/package
          git clone https://github.com/kiddin9/openwrt-packages

      - name: Update Target.mk
        run: |
          cd R5s/friendlywrt/include
          sed -i 's/dnsmasq /dnsmasq-full default-settings luci /' target.mk

      - name: Update Feeds
        run: |
          cd R5s/friendlywrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Install Mods
        run: |
          cd R5s

      - name: Patch
        run: |
          cp ./patches/9*.patch ./R5s/friendlywrt/target/linux/generic/hack-5.10/

      - name: Custom Configure Files
        run: |
          rm -rf ./R5s/configs/*
          cp -r ./config/* ./R5s/configs/

      - name: Set Default Values
        run: |
          cd R5s/friendlywrt

      - name: Build OpenWrt
        run: |
          cd R5s
          ./build.sh nanopi_r5s.mk

      - name: Fix Rootfs Owner and Group
        run: |
          sudo df -lh

      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/

          find R5s/out/ -name "FriendlyWrt_*img*" | xargs -I{} sh -c 'f=$(basename $1); zip -r -j "./artifact/${f}.zip" $1' sh {} \;

          cp R5s/friendlywrt/.config ./artifact/

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: FriendlyWrt_NanoPi-R5S rk3568 v22.03
          path: ./artifact/
